---
- name: Ensuring glance service ceph config subdir exists
  vars:
    service: "{{ glance_services['glance-api'] }}"
  file:
    path: "{{ node_config_directory }}/glance-api/ceph"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when: service | service_enabled_and_mapped_to_host

- name: Copy over ceph configs for Glance
  template:
    src: "ceph.conf.j2"
    dest: "{{ node_config_directory }}/glance-api/ceph/ceph.conf"
    mode: "0660"
  become: true
  when: inventory_hostname in groups['glance-api']

- name: Copy over ceph keyring for Glance
  template:
    src: "ceph.client.glance.keyring.j2"
    dest: "{{ node_config_directory }}/glance-api/ceph/ceph.client.glance.keyring"
    mode: "0660"
  become: true
  when: inventory_hostname in groups['glance-api']

- name: Ensuring config directory has correct owner and permission
  file:
    path: "{{ node_config_directory }}/glance-api"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  become: true
  when: inventory_hostname in groups['glance-api']
